// ═══════════════════════════════════════════
//  ENGLISH QUESTIONS
// ═══════════════════════════════════════════

const SUBJECTS_EN = {

  // ══════════════════════════════════════════════════════
  //  COMPUTER SCIENCE
  // ══════════════════════════════════════════════════════
  informatique: {
    label: "Computer Science",
    icon: "fa-solid fa-laptop-code",
    color: "#4f46e5",
    categories: [

      {
        name: "Networks",
        questions: [
          { question: "Which OSI model layer is responsible for routing packets?", choices: ["Transport Layer", "Network Layer", "Data Link Layer", "Application Layer"], correct: 1, explanation: "Layer 3 (Network) handles logical addressing and routing of packets between different networks." },
          { question: "Which protocol automatically assigns IP addresses?", choices: ["DNS", "FTP", "DHCP", "HTTP"], correct: 2, explanation: "DHCP (Dynamic Host Configuration Protocol) automatically assigns IP addresses to machines on a network." },
          { question: "What port does HTTPS use by default?", choices: ["80", "21", "443", "8080"], correct: 2, explanation: "HTTPS uses port 443, while HTTP uses port 80." },
          { question: "What is the Class A private IP address range?", choices: ["172.16.0.0 – 172.31.255.255", "192.168.0.0 – 192.168.255.255", "10.0.0.0 – 10.255.255.255", "127.0.0.0 – 127.255.255.255"], correct: 2, explanation: "The range 10.0.0.0/8 corresponds to Class A private addresses (RFC 1918)." },
          { question: "What is the main difference between TCP and UDP?", choices: ["TCP is faster than UDP", "UDP is reliable and TCP is not", "TCP guarantees packet delivery, UDP does not", "UDP is only for emails"], correct: 2, explanation: "TCP is connection-oriented and guarantees ordered delivery. UDP is connectionless and offers no delivery guarantee." },
          { question: "Which network model has 4 layers (Application, Transport, Internet, Network Access)?", choices: ["OSI Model", "TCP/IP Model", "IEEE 802 Model", "X.25 Model"], correct: 1, explanation: "The TCP/IP model has 4 layers, compared to 7 for the OSI model." },
          { question: "What is Network Address Translation (NAT)?", choices: ["A dynamic routing protocol", "A technique that maps private IP addresses to a public address", "A type of firewall", "A network encryption protocol"], correct: 1, explanation: "NAT allows multiple machines on a private network to share one or more public IP addresses." },
          { question: "Which protocol resolves a domain name to an IP address?", choices: ["FTP", "SMTP", "DNS", "SNMP"], correct: 2, explanation: "DNS (Domain Name System) translates domain names into numeric IP addresses." },
          { question: "How many bits does an IPv6 address contain?", choices: ["32 bits", "64 bits", "128 bits", "256 bits"], correct: 2, explanation: "An IPv6 address is 128 bits long, compared to 32 bits for IPv4." },
          { question: "What is a VPN?", choices: ["A private network virus", "A virtual private network that secures and encrypts the internet connection", "A file transfer protocol", "A type of network switch"], correct: 1, explanation: "A VPN creates an encrypted tunnel between the user and a server, masking the IP and securing data." },
          { question: "What wireless technology operates on 2.4 GHz and 5 GHz frequencies?", choices: ["Bluetooth", "Wi-Fi (IEEE 802.11)", "4G LTE", "Zigbee"], correct: 1, explanation: "Wi-Fi (IEEE 802.11) uses the 2.4 GHz and 5 GHz bands." },
          { question: "What does ICMP stand for?", choices: ["Internet Control Message Protocol", "Internal Computer Message Protocol", "Integrated Circuit Management Protocol", "Internet Communication Module Protocol"], correct: 0, explanation: "ICMP is used for network diagnostic messages such as ping requests." },
          { question: "Which protocol is used to send emails?", choices: ["IMAP", "POP3", "SMTP", "FTP"], correct: 2, explanation: "SMTP (Simple Mail Transfer Protocol) is used for sending emails. IMAP and POP3 are used for receiving." },
          { question: "What is bandwidth in a network?", choices: ["The maximum length of a network cable", "The number of simultaneously connected devices", "The amount of data that can be transmitted per unit time", "The network latency"], correct: 2, explanation: "Bandwidth represents the maximum transmission capacity, typically in bits per second." },
          { question: "What is the ARP protocol?", choices: ["It resolves an IP address to a MAC address on a local network", "It dynamically assigns IP addresses", "It routes packets between networks", "It encrypts network communications"], correct: 0, explanation: "ARP (Address Resolution Protocol) finds the MAC address corresponding to an IP address on the same local network." },
        ]
      },

      {
        name: "Algorithms & Data Structures",
        questions: [
          { question: "What is the worst-case time complexity of Quick Sort?", choices: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], correct: 2, explanation: "In the worst case (already sorted array with a bad pivot), Quick Sort reaches O(n²). Its average complexity is O(n log n)." },
          { question: "What data structure follows the LIFO principle?", choices: ["Queue", "Array", "Stack", "Linked List"], correct: 2, explanation: "The stack follows the LIFO principle: Last In, First Out." },
          { question: "Which search algorithm requires the array to be sorted?", choices: ["Linear search", "Binary search", "Hash search", "Sequential search"], correct: 1, explanation: "Binary search divides the search space in half at each step and requires a sorted array." },
          { question: "What is the average-case complexity of searching in a hash table?", choices: ["O(n)", "O(n²)", "O(log n)", "O(1)"], correct: 3, explanation: "On average, searching in a hash table is O(1) — constant time." },
          { question: "What data structure is used to efficiently implement a priority queue?", choices: ["Stack", "Sorted array", "Heap", "Graph"], correct: 2, explanation: "A heap is a binary tree that allows priority queue operations in O(log n)." },
          { question: "What is the best-case complexity of insertion sort?", choices: ["O(n²)", "O(n log n)", "O(n)", "O(1)"], correct: 2, explanation: "In the best case (already sorted array), insertion sort is O(n)." },
          { question: "What is the difference between DFS and BFS?", choices: ["DFS uses a queue, BFS uses a stack", "DFS explores depth-first, BFS explores breadth-first", "BFS is always faster", "DFS cannot find the shortest path"], correct: 1, explanation: "DFS dives as deep as possible before backtracking. BFS explores all neighbors layer by layer." },
          { question: "What is dynamic programming?", choices: ["A paradigm that uses dynamic variables", "A technique that decomposes a problem into subproblems and memoizes results", "A way to program animations", "A type of just-in-time compilation"], correct: 1, explanation: "Dynamic programming solves problems by memoizing subproblem results to avoid redundant calculations." },
          { question: "Which sorting algorithm is based on recursive division into halves and merging?", choices: ["Bubble Sort", "Insertion Sort", "Merge Sort", "Selection Sort"], correct: 2, explanation: "Merge Sort recursively divides, sorts each half, then merges. Complexity O(n log n) in all cases." },
          { question: "In a binary search tree (BST), where are values less than the root located?", choices: ["On the right", "On the left", "At the top", "In the center"], correct: 1, explanation: "In a BST, values less than the root are in the left subtree, greater values on the right." },
          { question: "What is a directed acyclic graph (DAG)?", choices: ["A graph without vertices", "A directed graph with no cycles", "A graph with only cycles", "A disconnected graph"], correct: 1, explanation: "A DAG (Directed Acyclic Graph) is a directed graph with no cycles, used to represent dependencies." },
          { question: "What is Big O notation?", choices: ["An object-oriented language", "A measure of an algorithm's complexity as a function of input size", "A sorting algorithm", "A network protocol"], correct: 1, explanation: "Big O describes the (time or space) complexity in the worst case as a function of n, the input size." },
          { question: "What is a doubly linked list?", choices: ["A list with two separate lists", "A list where each node points to both the next and previous node", "A list sorted in both directions", "A list with duplicates"], correct: 1, explanation: "In a doubly linked list, each node has a reference to both the next and previous node." },
          { question: "What is the principle of Radix Sort?", choices: ["It sorts by successive comparisons", "It sorts digit by digit starting from the least significant digit", "It divides the array in half at each step", "It uses a heap to sort"], correct: 1, explanation: "Radix Sort processes numbers digit by digit, from units to higher orders, without direct comparisons. Complexity O(nk)." },
          { question: "What is Dijkstra's algorithm?", choices: ["A sorting algorithm", "An algorithm that finds the shortest path between two nodes in a positively weighted graph", "A compression algorithm", "An encryption algorithm"], correct: 1, explanation: "Dijkstra computes the shortest path from a source node to all other nodes in a weighted graph with positive edges." },
        ]
      },

      {
        name: "Databases",
        questions: [
          { question: "Which SQL command retrieves data?", choices: ["INSERT", "UPDATE", "SELECT", "DELETE"], correct: 2, explanation: "SELECT queries and retrieves data from a relational database." },
          { question: "What is a primary key?", choices: ["An access password", "A unique identifier for each record", "A mandatory column", "A secondary index"], correct: 1, explanation: "The primary key uniquely identifies each record — it cannot be NULL or duplicated." },
          { question: "What does ACID stand for in the context of databases?", choices: ["Atomicity, Consistency, Isolation, Durability", "Association, Creation, Indexing, Duplication", "Automatic, Controlled, Integrated, Distributed", "Access, Connection, Integrity, Data"], correct: 0, explanation: "ACID guarantees transaction reliability: Atomicity, Consistency, Isolation, Durability." },
          { question: "Which type of JOIN returns only matching rows from both tables?", choices: ["LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN", "INNER JOIN"], correct: 3, explanation: "INNER JOIN returns only rows that have a match in both tables." },
          { question: "What is an index in a database?", choices: ["An alphabetical list of tables", "A structure that speeds up searches on one or more columns", "A database summary", "A type of join"], correct: 1, explanation: "An index (often a B-tree) allows rapid location of records without scanning the entire table." },
          { question: "What is database normalization?", choices: ["Conversion to lowercase", "A process to reduce redundancy and improve integrity", "Data compression", "Removal of unused tables"], correct: 1, explanation: "Normalization applies normal forms (1NF, 2NF, 3NF…) to eliminate redundancies." },
          { question: "What is a trigger?", choices: ["An admin button", "A procedure that executes automatically in response to a DML event", "A type of constraint", "A backup command"], correct: 1, explanation: "A trigger executes automatically before or after an INSERT, UPDATE, or DELETE on a table." },
          { question: "What is sharding?", choices: ["An encryption technique", "Dividing a database into partitions spread across multiple servers", "A type of incremental backup", "A sorting algorithm"], correct: 1, explanation: "Sharding horizontally partitions data across multiple servers to improve scalability." },
          { question: "What is the difference between a relational database and NoSQL?", choices: ["NoSQL is always faster", "Relational databases use SQL tables, NoSQL uses various formats (documents, key-value…)", "NoSQL does not store structured data", "Relational databases don't support transactions"], correct: 1, explanation: "Relational DBs (MySQL, PostgreSQL) have fixed schemas. NoSQL (MongoDB, Redis) offer more flexibility." },
          { question: "What is a VIEW in SQL?", choices: ["A physical copy of a table", "A saved SELECT query usable as a virtual table", "A type of index", "An automatic report"], correct: 1, explanation: "A view is a stored query under a name. It behaves like a virtual table without duplicating data." },
          { question: "What is a transaction in a database?", choices: ["A simple SELECT query", "A set of operations treated as an indivisible unit", "A database connection", "A type of backup"], correct: 1, explanation: "A transaction groups multiple operations that execute completely (commit) or not at all (rollback), ensuring atomicity." },
          { question: "What is the role of an ORM (Object-Relational Mapper)?", choices: ["Optimize SQL queries", "Map objects of a programming language to database tables", "Manage database connections", "Encrypt data in the database"], correct: 1, explanation: "An ORM (e.g. Hibernate, SQLAlchemy, Eloquent) allows database manipulation via objects without writing raw SQL." },
        ]
      },

      {
        name: "Programming",
        questions: [
          { question: "What is Object-Oriented Programming (OOP)?", choices: ["A paradigm based on mathematical functions", "A paradigm based on objects grouping data and behaviors", "A programming language", "A type of database"], correct: 1, explanation: "OOP organizes code into objects that encapsulate data (attributes) and behaviors (methods). Pillars: encapsulation, inheritance, polymorphism, abstraction." },
          { question: "What is polymorphism in OOP?", choices: ["The ability of an object to change type", "The ability of multiple classes to implement the same interface differently", "Multiple inheritance", "Copying an object"], correct: 1, explanation: "Polymorphism allows objects of different classes to respond to the same interface, each in their own way." },
          { question: "What does the 'static' keyword do in a Java class method?", choices: ["Makes the method private", "The method belongs to the class, not an instance", "Prevents inheritance", "Makes the method faster"], correct: 1, explanation: "A 'static' method belongs to the class, not an instance. It is called directly using the class name." },
          { question: "What is a garbage collector?", choices: ["A file cleanup tool", "An automatic mechanism that frees memory from unused objects", "A code analysis tool", "A compression process"], correct: 1, explanation: "The garbage collector automatically frees memory occupied by objects no longer referenced (Java, Python, C#…)." },
          { question: "What does the DRY principle mean?", choices: ["Develop Rapidly Yolo", "Don't Repeat Yourself — avoid code duplication", "Design Responsive Yesterday", "Data Relational Yield"], correct: 1, explanation: "DRY (Don't Repeat Yourself) advocates eliminating duplications: every piece of logic should have a single representation." },
          { question: "What is functional programming?", choices: ["A paradigm that uses pure mathematical functions without side effects", "Programming Windows functions", "An object-oriented paradigm", "Network programming"], correct: 0, explanation: "Functional programming uses pure functions (same input → same output), immutability and higher-order functions." },
          { question: "What is a closure in programming?", choices: ["A function that closes the program", "A function that captures variables from its lexical environment", "A type of exception", "A private method"], correct: 1, explanation: "A closure is a function that 'captures' variables from the scope in which it was defined, even after that scope has disappeared." },
          { question: "What is the difference between a compiled and interpreted language?", choices: ["A compiled language is more recent", "A compiled language is translated to machine code before execution, an interpreted one is translated line by line at runtime", "An interpreted language is faster", "No practical difference"], correct: 1, explanation: "Compiled languages (C, C++, Rust) produce a binary executable. Interpreted languages (Python, JavaScript) are translated on the fly during execution." },
          { question: "What is tail recursion?", choices: ["A recursion that never ends", "A form of recursion where the recursive call is the last operation, optimizable by the compiler", "A type of recursive loop", "A recursion with multiple base cases"], correct: 1, explanation: "Tail recursion places the recursive call as the last instruction. Compilers can optimize it into a loop, avoiding stack overflow." },
          { question: "What is the Singleton design pattern?", choices: ["A pattern that creates a unique copy of an object", "A pattern that ensures a class has only one instance and provides a global access point", "A pattern for creating families of objects", "A communication pattern between objects"], correct: 1, explanation: "The Singleton ensures a class is only instantiated once. Useful for configurations, DB connections, loggers." },
          { question: "What is dependency injection?", choices: ["A software attack technique", "A design pattern where an object's dependencies are provided externally", "A type of inheritance", "A unit testing method"], correct: 1, explanation: "Dependency injection decouples components by providing their dependencies externally rather than creating them internally, facilitating testing and maintainability." },
          { question: "What does the reactive programming paradigm represent?", choices: ["A style based on event loops", "A paradigm centered on asynchronous data streams and change propagation", "A type of object-oriented programming", "A parallel programming paradigm"], correct: 1, explanation: "Reactive programming (RxJS, Reactor…) models data as observable streams. Changes automatically propagate to subscribers." },
        ]
      },

      {
        name: "Computer Security",
        questions: [
          { question: "What is an SQL injection attack?", choices: ["A physical attack on a server", "Inserting malicious SQL code to manipulate the database", "A virus that corrupts SQL files", "A backup technique"], correct: 1, explanation: "SQL injection inserts malicious SQL code into input fields to manipulate or illegally access the database." },
          { question: "What does the CIA triad represent in security?", choices: ["Control, Integration, Authentication", "Confidentiality, Integrity, Availability", "Encryption, Identification, Authorization", "Connection, Isolation, Access"], correct: 1, explanation: "The CIA triad: Confidentiality (authorized access), Integrity (data not altered), Availability (guaranteed access to legitimate users)." },
          { question: "What is ransomware?", choices: ["Network monitoring software", "Malware that encrypts files and demands a ransom", "A type of firewall", "An authentication protocol"], correct: 1, explanation: "Ransomware encrypts the victim's data and demands a ransom (often in cryptocurrency) for the decryption key." },
          { question: "What is an XSS vulnerability?", choices: ["An attack on DNS servers", "Injecting malicious scripts into a web page viewed by other users", "A flaw in network protocols", "A virus targeting browsers"], correct: 1, explanation: "XSS (Cross-Site Scripting) injects malicious JavaScript into a web page. It executes in visitors' browsers." },
          { question: "What is two-factor authentication (2FA)?", choices: ["A double password", "A method that combines two different types of verification", "Two linked accounts", "Two-key encryption"], correct: 1, explanation: "2FA combines two factors: something you know (password) and something you possess (SMS code, physical key)." },
          { question: "What is a penetration test (pentest)?", choices: ["A network speed test", "An authorized simulated attack to identify vulnerabilities", "A source code audit", "A load test"], correct: 1, explanation: "A pentest is an ethical cyberattack performed by experts to identify vulnerabilities before real attackers do." },
          { question: "What is the principle of least privilege?", choices: ["Give maximum rights to everyone", "Grant only the necessary rights to each user", "Remove all rights", "Share the same rights among everyone"], correct: 1, explanation: "PoLP (Principle of Least Privilege) limits rights to the strict minimum, reducing the attack surface in case of compromise." },
          { question: "What is a Man-in-the-Middle (MitM) attack?", choices: ["A physical attack on a cable", "An attacker secretly intercepting a communication", "A RAM virus", "A brute force attack"], correct: 1, explanation: "In a MitM attack, the attacker intercepts and can read, modify or inject data between two parties without their knowledge." },
          { question: "What is a SIEM?", choices: ["A next-generation firewall", "A system that collects, analyzes and correlates security events in real time", "A centralized antivirus", "An encryption protocol"], correct: 1, explanation: "A SIEM (Security Information and Event Management) centralizes logs, detects suspicious behavior and aids incident response." },
          { question: "What is the OWASP Top 10?", choices: ["A ranking of the best hackers", "A list of the 10 most critical security risks for web applications", "An encryption standard", "An authentication protocol"], correct: 1, explanation: "The OWASP Top 10 lists the most common web vulnerabilities (injection, XSS, broken authentication…) to help developers avoid them." },
          { question: "What is asymmetric encryption?", choices: ["Encryption with a single shared key", "Encryption using a key pair: a public key to encrypt, a private key to decrypt", "Encryption based on random sequences", "Encryption used only for emails"], correct: 1, explanation: "Asymmetric encryption (RSA, ECC) uses a public key to encrypt and a private key to decrypt. Basis of HTTPS and digital signatures." },
          { question: "What is Social Engineering?", choices: ["Engineering of social networks", "Psychological manipulation of people to obtain confidential information", "A type of network attack", "A collaborative development technique"], correct: 1, explanation: "Social Engineering exploits human psychology (trust, fear, urgency) rather than technical vulnerabilities to gain access or information." },
        ]
      },

      {
        name: "Operating Systems",
        questions: [
          { question: "What is a process in computing?", choices: ["A file on disk", "A running program with its allocated resources", "A type of RAM memory", "A network protocol"], correct: 1, explanation: "A process is a running program. It has its own memory space, open files and context." },
          { question: "What is a deadlock?", choices: ["A bug that causes a reboot", "A situation where processes wait for each other indefinitely", "A type of network attack", "A security mechanism"], correct: 1, explanation: "A deadlock occurs when processes block each other because each is waiting for a resource held by another." },
          { question: "What is paging in memory management?", choices: ["Displaying web pages", "Dividing memory into fixed-size blocks to facilitate allocation", "Numbering system files", "A type of compression"], correct: 1, explanation: "Paging divides physical and virtual memory into fixed-size pages, allowing non-contiguous allocation." },
          { question: "What is the OS kernel?", choices: ["The graphical interface", "The core of the OS that directly manages hardware and system resources", "The integrated antivirus", "The file manager"], correct: 1, explanation: "The kernel runs in privileged mode and directly manages memory, processes, devices and system calls." },
          { question: "Which Linux command displays running processes?", choices: ["ls", "pwd", "ps", "cd"], correct: 2, explanation: "The 'ps' command displays active processes. 'top' and 'htop' provide a dynamic real-time view." },
          { question: "What is virtual memory?", choices: ["RAM that doesn't physically exist", "A technique that uses disk space as an extension of RAM", "A type of cache memory", "Memory of virtual machines"], correct: 1, explanation: "Virtual memory allows programs to use more memory than available RAM by using part of the disk (swap)." },
          { question: "What is the difference between a process and a thread?", choices: ["A thread is heavier", "A process has its own isolated memory space, threads share their process's memory", "Threads cannot run in parallel", "A process is a subunit of a thread"], correct: 1, explanation: "A process is isolated with its own memory space. Threads within the same process share memory." },
          { question: "What is a hypervisor?", choices: ["A high-performance processor", "Software that creates and manages virtual machines", "An advanced file system", "A network virtualization protocol"], correct: 1, explanation: "A hypervisor (VMware, VirtualBox, KVM) creates and manages VMs by sharing physical resources among multiple guest OS." },
          { question: "What is process scheduling?", choices: ["Planning backups", "The mechanism that decides which process uses the CPU and for how long", "Managing print queues", "Automatic updates"], correct: 1, explanation: "The scheduler decides the order and time of CPU usage by processes, using algorithms like Round Robin or FIFO." },
          { question: "What is a system call (syscall)?", choices: ["An emergency phone call", "An interface allowing user programs to request services from the kernel", "A type of network protocol", "A system startup command"], correct: 1, explanation: "A system call is the mechanism by which a user-mode program requests a service from the kernel (read a file, allocate memory…)." },
          { question: "What is protected mode in x86 processors?", choices: ["A network security mode", "An execution mode that enables memory protection and multitasking with privilege levels", "A low-power mode", "A debugging mode"], correct: 1, explanation: "Protected mode (as opposed to real mode) enables segmentation, paging, multitasking and privilege rings (ring 0/3) on x86 processors." },
        ]
      },

      {
        name: "Web Development",
        questions: [
          { question: "What does HTML stand for?", choices: ["HyperText Markup Language", "High Tech Modern Language", "HyperText Machine Language", "Hybrid Text Markup Language"], correct: 0, explanation: "HTML (HyperText Markup Language) is the standard markup language for creating the structure of web pages." },
          { question: "What is the DOM in JavaScript?", choices: ["A programming language", "The object representation of the HTML structure, manipulable in JavaScript", "A communication protocol", "A type of web database"], correct: 1, explanation: "The DOM (Document Object Model) represents the HTML page as a tree of objects. JS can manipulate it to dynamically modify the page." },
          { question: "What is the difference between GET and POST in HTTP?", choices: ["GET is more secure", "GET sends parameters in the URL, POST sends them in the request body", "POST is reserved for files", "GET cannot send data"], correct: 1, explanation: "GET transmits parameters in the URL (visible, size-limited). POST sends them in the body (not visible in URL, suitable for forms)." },
          { question: "What is responsive design?", choices: ["A design that responds to clicks", "An approach that adapts the interface to different screen sizes", "A JavaScript framework", "A CSS animation technique"], correct: 1, explanation: "Responsive design uses CSS media queries, flexible grids and fluid images to automatically adapt the interface." },
          { question: "What is the WebSocket protocol?", choices: ["A file transfer protocol", "A bidirectional real-time communication protocol over a persistent TCP connection", "An extension of HTTP", "A web encryption protocol"], correct: 1, explanation: "WebSocket enables full-duplex real-time communication over a persistent TCP connection, ideal for chats and online games." },
          { question: "What does the HTML <meta name='viewport'> tag do?", choices: ["It defines the page title", "It controls display on mobile devices", "It adds SEO metadata only", "It links a CSS file"], correct: 1, explanation: "The viewport tag controls dimensions and scale on mobile, essential for responsive design." },
          { question: "What is Node.js?", choices: ["A front-end JavaScript framework", "A server-side JavaScript runtime built on the V8 engine", "A database management system", "A programming language"], correct: 1, explanation: "Node.js allows running JavaScript server-side via the V8 engine. Its event-driven non-blocking model suits real-time apps." },
          { question: "What does CORS stand for?", choices: ["Cross-Origin Resource Sharing — mechanism allowing access to resources from a different domain", "Common Object Request System", "Cross-Origin Response Security", "Client-Oriented Resource Server"], correct: 0, explanation: "CORS is a browser security policy. Servers enable it via specific HTTP headers." },
          { question: "What is GraphQL?", choices: ["A type of graph database", "A query language for APIs that allows requesting exactly the needed data", "A CSS framework", "An HTTP cache protocol"], correct: 1, explanation: "GraphQL (created by Meta) is a query language for APIs allowing the client to specify exactly the data it needs, avoiding over/under-fetching." },
          { question: "What is an HTTP cookie?", choices: ["A server configuration file", "A small data file stored by the browser and sent with each request", "A type of server session", "A caching technique"], correct: 1, explanation: "A cookie is a small text file stored by the browser allowing state to be maintained between requests (sessions, preferences, tracking)." },
          { question: "What is SSR (Server-Side Rendering)?", choices: ["A type of web server", "Rendering the HTML page server-side before sending to the client", "A security protocol", "A type of database"], correct: 1, explanation: "SSR generates HTML server-side on each request (Next.js, Nuxt.js). Better SEO and initial display time, but higher server load." },
          { question: "What is a JWT (JSON Web Token)?", choices: ["A JSON file format", "A compact, signed token to transmit information between parties in a verifiable way", "A type of secure cookie", "A network authentication protocol"], correct: 1, explanation: "A JWT has three parts (header, payload, signature) encoded in Base64. It enables stateless authentication without server sessions." },
        ]
      },

      {
        name: "Cloud & DevOps",
        questions: [
          { question: "What does IaaS stand for?", choices: ["Infrastructure as a Service — virtualized hardware resources on demand", "Integration as a Service", "Internet as a System", "Intelligent Automation as a Service"], correct: 0, explanation: "IaaS provides virtualized resources (servers, storage, network) on demand. Examples: AWS EC2, Azure VMs." },
          { question: "What is Docker?", choices: ["A cloud programming language", "A containerization tool that packages an application and its dependencies", "A cloud provider", "A lightweight operating system"], correct: 1, explanation: "Docker creates portable containers encapsulating an application and its dependencies, ensuring identical behavior across any environment." },
          { question: "What is Kubernetes?", choices: ["A cloud language", "A container orchestration tool for deployment and management at scale", "A cloud storage service", "A network monitoring system"], correct: 1, explanation: "Kubernetes (K8s) automates deployment, scaling and management of containers. It ensures availability and handles failures." },
          { question: "What is Continuous Integration (CI)?", choices: ["Integration of cloud services", "The practice of frequently integrating code with automatic verification", "A manual deployment method", "A performance test"], correct: 1, explanation: "CI regularly integrates code into a shared repository and automatically triggers builds and tests to detect errors early." },
          { question: "What is Infrastructure as Code (IaC)?", choices: ["Programming processors", "Managing infrastructure via versioned configuration files", "A type of cloud container", "Programming firmware"], correct: 1, explanation: "IaC (Terraform, CloudFormation) defines infrastructure in versionable, reproducible and automatable code." },
          { question: "What is load balancing?", choices: ["Cloud compression", "Distributing traffic across multiple servers to optimize performance and availability", "A type of cloud backup", "Bandwidth management"], correct: 1, explanation: "A load balancer distributes requests across multiple servers, avoiding overload and ensuring high availability." },
          { question: "What is a microservices architecture?", choices: ["A very lightweight application", "A style that decomposes an application into independent services communicating via APIs", "A minimal Docker container", "An OS for microprocessors"], correct: 1, explanation: "Microservices decompose an application into independent services (auth, payment, catalog…), each deployable separately." },
          { question: "What is serverless computing?", choices: ["A cloud without physical servers", "A model where the developer deploys code without managing infrastructure", "A type of lightweight virtualization", "A distributed system without a central point"], correct: 1, explanation: "Serverless (AWS Lambda, Azure Functions) executes code on demand without server management. Billed per usage." },
          { question: "What is GitOps?", choices: ["An advanced version manager", "An approach where Git is the single source of truth for infrastructure deployments", "A type of CI/CD pipeline", "A Git monitoring tool"], correct: 1, explanation: "GitOps uses Git as the source of truth for infrastructure and deployments. Changes in Git automatically trigger production updates." },
          { question: "What is a container registry?", choices: ["A monitoring tool", "A centralized repository to store and distribute Docker images", "A type of cloud database", "A Kubernetes pod manager"], correct: 1, explanation: "A registry (Docker Hub, ECR, GCR) stores and distributes container images. Teams publish and retrieve versioned images." },
        ]
      },

      {
        name: "Artificial Intelligence",
        questions: [
          { question: "What is machine learning?", choices: ["Manually programming rules", "A field of AI where systems learn from data without being explicitly programmed", "An advanced sorting algorithm", "A type of intelligent database"], correct: 1, explanation: "Machine learning allows systems to learn and improve automatically from data." },
          { question: "What is overfitting?", choices: ["A model too simple", "When a model memorizes training data and generalizes poorly to new data", "A lack of data", "A speed problem"], correct: 1, explanation: "Overfitting occurs when a model memorizes the noise in training data and performs poorly on new data." },
          { question: "What is an LLM?", choices: ["A type of database", "A deep learning model trained on large amounts of text to generate and understand language", "A text compression algorithm", "A network protocol"], correct: 1, explanation: "An LLM (Large Language Model) is based on the Transformer architecture. Examples: GPT, Claude, Gemini, LLaMA." },
          { question: "What is reinforcement learning?", choices: ["Learning with labeled data", "A type where an agent learns by interacting with an environment and receiving rewards/penalties", "A clustering algorithm", "A regression technique"], correct: 1, explanation: "In reinforcement learning, an agent maximizes cumulative reward through its actions. Used in AlphaGo, robotics, autonomous vehicles." },
          { question: "What is gradient descent?", choices: ["A sorting algorithm", "An optimization algorithm that adjusts parameters to minimize the loss function", "A visualization technique", "A network protocol"], correct: 1, explanation: "Gradient descent iteratively adjusts weights in the opposite direction of the gradient of the loss function to reduce error." },
          { question: "What is transfer learning?", choices: ["Transferring data between models", "Reusing a pre-trained model on a task and adapting it to a new task", "A type of unsupervised learning", "Copying a neural network"], correct: 1, explanation: "Transfer learning reuses representations learned by a pre-trained model (e.g. BERT, ResNet) and fine-tunes them for a specific task." },
          { question: "What is the Transformer architecture?", choices: ["A type of electronic circuit", "A neural network architecture based on attention, at the core of modern LLMs", "An optimized compiler", "A type of vector database"], correct: 1, explanation: "The Transformer architecture (Vaswani et al., 2017) uses the attention mechanism to process sequences in parallel. It underlies BERT, GPT, etc." },
          { question: "What is a Convolutional Neural Network (CNN)?", choices: ["A network optimized for text processing", "A network specialized in processing images via convolutional filters", "A recurrent network", "A neural network for graphs"], correct: 1, explanation: "CNNs use convolution layers to detect local features in images (edges, textures, shapes). Widely used in computer vision." },
          { question: "What is NLP?", choices: ["A network protocol", "A field of AI for understanding, interpreting and generating human language", "A type of textual encryption", "A compression technique"], correct: 1, explanation: "NLP (Natural Language Processing) enables machines to analyze and generate human language. It underlies chatbots, translators and voice assistants." },
          { question: "What is RAG (Retrieval-Augmented Generation)?", choices: ["A type of recurrent network", "A technique combining information retrieval and text generation to improve LLMs", "A training algorithm", "A type of training data"], correct: 1, explanation: "RAG improves LLMs by retrieving relevant documents from an external knowledge base before generating a response, reducing hallucinations." },
        ]
      },

      {
        name: "Architecture & Hardware",
        questions: [
          { question: "What is the ALU in a processor?", choices: ["Arithmetic Logic Unit — performs arithmetic and logical operations", "Advanced Loading Unit", "Automatic Link Updater", "Application Layer Unit"], correct: 0, explanation: "The ALU performs arithmetic (addition, subtraction) and logical (AND, OR, NOT) operations of the processor." },
          { question: "What is the difference between a CPU and a GPU?", choices: ["The GPU is always more powerful", "The CPU is optimized for sequential tasks, the GPU for massive parallel computations", "The GPU manages RAM", "CPU and GPU do the same work"], correct: 1, explanation: "The CPU has few powerful cores for sequential tasks. The GPU has thousands of small cores for massive parallel processing." },
          { question: "What is pipelining in processor architecture?", choices: ["A CPU-RAM cable", "A technique allowing multiple instructions to be executed overlapping in time", "A type of cache", "A CPU-GPU protocol"], correct: 1, explanation: "Pipelining divides instruction execution into stages (fetch, decode, execute, write-back) allowing multiple instructions to be simultaneously in progress." },
          { question: "What is the difference between HDD and SSD?", choices: ["SSD is less reliable", "HDD uses rotating magnetic platters, SSD uses flash memory", "HDD is faster", "They are technically identical"], correct: 1, explanation: "HDD: rotating magnetic platters — cheaper, slower, fragile. SSD: flash memory — faster, silent, shock-resistant, more expensive." },
          { question: "What is RISC architecture?", choices: ["Reduced Instruction Set Computer — processor with a simple, reduced instruction set", "Rapid Instruction Speed Computer", "Real-time Instruction Set Controller", "Remote Integrated System Circuit"], correct: 0, explanation: "RISC (Reduced Instruction Set Computer) uses simple instructions executed in one cycle. ARM is an iconic example, the basis of smartphones." },
          { question: "What is the PCIe interface?", choices: ["A network protocol", "A high-speed serial bus for connecting expansion cards (GPU, NVMe SSD) to the motherboard", "A power connector", "A USB protocol"], correct: 1, explanation: "PCIe is a high-speed serial bus for connecting GPUs, NVMe SSDs and other expansion cards to the motherboard." },
          { question: "What is processor cache memory?", choices: ["An automatic RAM backup", "Very fast memory integrated in the CPU for storing frequently used data", "A high-speed hard drive", "The GPU's video memory"], correct: 1, explanation: "Cache (L1, L2, L3) is ultra-fast and close to the CPU. It reduces access time to frequent data, avoiding round trips to RAM." },
          { question: "What does DDR5 RAM offer compared to DDR4?", choices: ["DDR5 is a different RAM brand", "DDR5 offers improved bandwidth and energy efficiency over DDR4", "DDR5 is slower but cheaper", "DDR5 uses the same physical form factor as DDR4"], correct: 1, explanation: "DDR5 doubles bandwidth and improves energy efficiency over DDR4. It uses a new slot format incompatible with DDR4." },
          { question: "What is branch prediction in a CPU?", choices: ["A debugging mechanism", "A technique where the processor predicts the result of a condition to continue execution without waiting", "A type of compiler optimization", "A memory caching technique"], correct: 1, explanation: "Branch prediction allows the CPU to continue executing instructions by anticipating the result of a conditional branch, improving pipeline throughput." },
          { question: "What is NUMA (Non-Uniform Memory Access)?", choices: ["A type of cache memory", "A multi-processor architecture where memory access time depends on the processor location", "A bus protocol", "A type of hard drive"], correct: 1, explanation: "In NUMA, each processor has local memory (fast access) and can access other processors' memory (slower). Common in multi-socket servers." },
        ]
      },

      {
        name: "Software Engineering",
        questions: [
          { question: "What is the Agile methodology?", choices: ["A waterfall development method", "A set of iterative practices for developing software flexibly", "A modern programming language", "A versioning tool"], correct: 1, explanation: "Agile (Scrum, Kanban…) is based on short iterations, collaboration and adaptation to change." },
          { question: "What is TDD (Test-Driven Development)?", choices: ["Tests are written after the code", "Tests are written before the code, guiding its development", "A type of integration test", "A testing framework"], correct: 1, explanation: "TDD follows the Red-Green-Refactor cycle: write a failing test, write minimal code to pass it, then refactor." },
          { question: "What is the SOLID principle?", choices: ["A sorting algorithm", "5 object-oriented design principles for maintainable code", "A testing framework", "A security protocol"], correct: 1, explanation: "SOLID: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion." },
          { question: "What is technical debt?", choices: ["The financial cost of a project", "The accumulation of imperfect quick solutions that increase future maintenance cost", "The number of unresolved bugs", "Delivery delay"], correct: 1, explanation: "Technical debt denotes quality compromises accepted to deliver faster. It accumulates and generates future overhead costs." },
          { question: "What is refactoring?", choices: ["Complete rewrite of an application", "Restructuring code without changing its behavior to improve readability and maintainability", "Creating automated tests", "Migration to a new language"], correct: 1, explanation: "Refactoring improves the internal structure of code without modifying its external behavior, secured by tests." },
          { question: "What is a UML diagram?", choices: ["A visual programming language", "A standardized modeling language for visualizing system design", "A graphical versioning tool", "A communication protocol between components"], correct: 1, explanation: "UML (Unified Modeling Language) offers various diagrams (class, sequence, use case…) to document systems." },
          { question: "What is the difference between CI, CD (Delivery) and CD (Deployment)?", choices: ["They are three names for the same thing", "CI integrates and tests, CD (delivery) prepares the release, CD (deployment) deploys automatically to production", "CI is manual, the others are automatic", "Only continuous deployment includes tests"], correct: 1, explanation: "CI: automatic integration and tests. Continuous Delivery: release ready to deploy manually. Continuous Deployment: automatic deployment to production after tests." },
          { question: "What is a sprint in Scrum?", choices: ["A performance test", "A fixed-duration development iteration (1-4 weeks) with defined objectives", "A weekly meeting", "An urgent deployment"], correct: 1, explanation: "A Scrum sprint is a fixed-duration iteration during which the team produces a potentially shippable increment." },
          { question: "What is code coverage?", choices: ["The number of lines of code", "The percentage of code executed during automated tests", "The quality of source code", "The number of developers working on the code"], correct: 1, explanation: "Code coverage measures the percentage of code executed by tests. High coverage reduces the risk of undetected bugs." },
          { question: "What is pair programming?", choices: ["Remote programming", "A practice where two developers work together on the same code in real time", "A type of asynchronous code review", "Programming in pairs on different tasks in parallel"], correct: 1, explanation: "Pair programming places two developers at the same screen: a 'driver' who codes, an 'observer' who reviews and thinks. Improves quality and knowledge sharing." },
        ]
      },

    ]
  },

  // ══════════════════════════════════════════════════════
  //  ELECTRONICS & EMBEDDED SYSTEMS
  // ══════════════════════════════════════════════════════
  electronique: {
    label: "Electronics & Embedded",
    icon: "fa-solid fa-microchip",
    color: "#d97706",
    categories: [

      {
        name: "Digital Electronics",
        questions: [
          { question: "What is an AND logic gate?", choices: ["Its output is 1 if at least one input is 1", "Its output is 1 only if all inputs are 1", "Its output is always the inverse of the input", "Its output is 1 if exactly one input is 1"], correct: 1, explanation: "The AND gate produces 1 only when all its inputs are 1. Truth table: 0&0=0, 0&1=0, 1&1=1." },
          { question: "What is a D flip-flop?", choices: ["A binary counter", "A memory element that stores 1 bit and updates on the clock edge", "An analog-to-digital converter", "A shift register"], correct: 1, explanation: "The D (Data) flip-flop captures its input D value on the rising (or falling) clock edge and holds it until the next cycle." },
          { question: "What does the binary number system represent?", choices: ["A base-8 number system", "A base-2 number system using only 0 and 1", "A color coding system", "A communication protocol"], correct: 1, explanation: "Binary uses only two digits (0 and 1) corresponding to the LOW and HIGH states of an electrical signal. Fundamental in computing and electronics." },
          { question: "What is CMOS logic?", choices: ["A type of processor", "An integrated circuit technology using complementary MOS transistors with low power consumption", "A serial communication standard", "A type of non-volatile memory"], correct: 1, explanation: "CMOS (Complementary Metal-Oxide-Semiconductor) combines NMOS and PMOS transistors. Its main characteristic is very low static power consumption." },
          { question: "What is a multiplexer (MUX)?", choices: ["A signal amplifier", "A circuit that selects one input from several and routes it to a single output", "A voltage converter", "A type of memory"], correct: 1, explanation: "A multiplexer selects one of N inputs and connects it to the output, controlled by select lines. A 4:1 MUX has 4 inputs, 1 output, 2 select lines." },
          { question: "What is a full adder?", choices: ["A circuit that adds two multi-bit numbers", "A combinational circuit that adds 3 bits (A, B, carry-in) and produces a sum and carry-out", "A complete arithmetic processor", "A type of register"], correct: 1, explanation: "A full adder adds A + B + Cin and produces Sum and Cout. Multiple full adders are cascaded to add multi-bit numbers." },
          { question: "What is the difference between a combinational and sequential circuit?", choices: ["Combinational circuits are faster", "A combinational circuit depends only on current inputs, a sequential one also on past state", "A sequential circuit doesn't use logic gates", "There is no fundamental difference"], correct: 1, explanation: "A combinational circuit (AND, OR, MUX) produces output determined only by current inputs. A sequential circuit (counter, register) stores state." },
          { question: "What is Gray code?", choices: ["An RGB color code", "A binary code where two successive values differ by only one bit", "A serial communication protocol", "A type of compressed data encoding"], correct: 1, explanation: "Gray code (or reflected binary) ensures two consecutive values differ by only one bit, reducing errors during transitions in encoders." },
          { question: "What is an ADC converter?", choices: ["A differential amplifier", "A component that converts a continuous analog signal into a discrete digital value", "A data bus controller", "A type of analog memory"], correct: 1, explanation: "An ADC (Analog-to-Digital Converter) samples and quantizes an analog signal into a digital value. Resolution (8, 12, 16 bits) determines precision." },
          { question: "What is a shift register?", choices: ["A type of RAM", "A sequential circuit that shifts bits from position to position on each clock cycle", "A binary counter", "A type of adder"], correct: 1, explanation: "A shift register stores a sequence of bits and shifts them one position on each clock cycle. Used for data serialization/deserialization." },
          { question: "What is a Karnaugh map?", choices: ["A standard truth table", "A graphical tool for simplifying boolean expressions and minimizing logic circuits", "A type of timing diagram", "A circuit testing protocol"], correct: 1, explanation: "The Karnaugh map (K-map) visually simplifies boolean functions by grouping adjacent 1s, reducing the number of required gates." },
          { question: "What is the I2C protocol?", choices: ["A two-wire serial bus standard (SDA, SCL) for communicating between components over short distances", "A type of Flash memory", "An embedded network protocol", "A digital voltage converter"], correct: 0, explanation: "I2C (Inter-Integrated Circuit) uses two wires: SDA (data) and SCL (clock). It allows multiple masters/slaves to communicate on the same bus with addressing." },
        ]
      },

      {
        name: "Embedded Systems",
        questions: [
          { question: "What is a microcontroller?", choices: ["A complete miniature computer integrating CPU, memory and peripherals on a single chip", "A high-performance processor", "A type of embedded operating system", "A programmable sensor"], correct: 0, explanation: "A microcontroller (Arduino UNO, STM32, ESP32…) integrates on a single chip: CPU, RAM, Flash, timers, GPIO, ADC, communication interfaces." },
          { question: "What is an RTOS (Real-Time Operating System)?", choices: ["An OS for real-time servers", "An operating system guaranteeing responses within strict and deterministic deadlines", "An embedded systems simulator", "A type of embedded compiler"], correct: 1, explanation: "An RTOS (FreeRTOS, VxWorks, Zephyr…) guarantees that critical tasks execute within a maximum guaranteed delay, essential for real-time systems." },
          { question: "What is the SPI protocol?", choices: ["A 4-wire synchronous serial bus (MOSI, MISO, SCK, CS) for high-speed communication", "A Flash memory standard", "An embedded network protocol", "A type of interrupt"], correct: 0, explanation: "SPI (Serial Peripheral Interface) uses 4 wires: MOSI (master→slave), MISO (slave→master), SCK (clock), CS (select). Faster than I2C, no addressing." },
          { question: "What is an interrupt in an embedded system?", choices: ["A critical error that stops the program", "A signal that suspends the main program to execute an interrupt service routine (ISR)", "A type of timer", "A debugging technique"], correct: 1, explanation: "An interrupt signals the CPU of an asynchronous event (button, timer, UART reception). The CPU suspends its task, executes the ISR, then resumes." },
          { question: "What is JTAG debugging?", choices: ["An embedded network protocol", "A test and debug interface standard that allows access to the internal state of the processor", "A type of Flash programmer", "A serial communication protocol"], correct: 1, explanation: "JTAG (IEEE 1149.1) is a debug interface that allows reading/writing registers, setting breakpoints and programming Flash without disassembling the circuit." },
          { question: "What is the CAN bus protocol?", choices: ["A network protocol for cameras", "A robust serial bus for communication between microcontrollers, widely used in automotive", "A type of embedded memory", "An OTA programming protocol"], correct: 1, explanation: "CAN (Controller Area Network) is a differential serial bus robust to electromagnetic interference, standard in automotive (ECU, ABS, airbags) and industry." },
          { question: "What is a bootloader in an embedded system?", choices: ["A desktop OS startup program", "A small program that runs at startup to initialize hardware and load the main firmware", "A type of embedded debugger", "A Flash memory manager"], correct: 1, explanation: "The bootloader runs first at startup. It initializes hardware, verifies firmware integrity and loads it into memory. It also enables firmware updates." },
          { question: "What is DMA (Direct Memory Access)?", choices: ["A type of direct RAM access", "A mechanism allowing peripherals to transfer data to memory without CPU intervention", "A memory bus protocol", "A type of interrupt controller"], correct: 1, explanation: "DMA allows peripherals (ADC, UART, SPI…) to transfer data directly to RAM without using the CPU, freeing it for other tasks." },
          { question: "What is a Watchdog Timer?", choices: ["A performance measurement timer", "A timer that automatically resets the system if the program doesn't refresh it periodically", "A type of external interrupt", "A clock cycle counter"], correct: 1, explanation: "The watchdog is a safety timer. If the program crashes or hangs and fails to refresh the watchdog in time, it triggers an automatic microcontroller reset." },
          { question: "What is Flash memory in embedded systems?", choices: ["Ultra-fast RAM memory", "Electrically erasable non-volatile memory that stores the microcontroller firmware", "A type of internal register", "Cache memory"], correct: 1, explanation: "Flash memory is non-volatile (retains data without power) and stores the program (firmware). It erases in blocks and has a limited number of write cycles." },
          { question: "What is the UART protocol?", choices: ["A high-speed parallel bus", "An asynchronous serial communication protocol using two wires (TX, RX)", "A type of network interrupt", "A JTAG debug protocol"], correct: 1, explanation: "UART (Universal Asynchronous Receiver-Transmitter) is the simplest serial protocol: TX sends, RX receives. No shared clock — both parties must have the same baud rate." },
          { question: "What is IoT (Internet of Things)?", choices: ["A type of private network", "The interconnection of physical objects equipped with sensors and connectivity to exchange data", "A machine-to-machine communication protocol", "A type of embedded operating system"], correct: 1, explanation: "IoT connects physical objects (sensors, actuators, devices) to the Internet to collect, analyze and act on data in real time." },
        ]
      },

      {
        name: "Signal Processing",
        questions: [
          { question: "What is the Fourier transform?", choices: ["A sorting algorithm", "A mathematical tool that decomposes a signal into its constituent frequencies", "A type of digital filter", "A modulation protocol"], correct: 1, explanation: "The Fourier transform converts a signal from the time domain to the frequency domain, revealing the frequencies that compose the signal." },
          { question: "What is the Shannon-Nyquist theorem?", choices: ["A theorem on algorithm complexity", "A theorem stating that the sampling frequency must be at least twice the maximum frequency of the signal", "A data compression theorem", "A cryptography principle"], correct: 1, explanation: "The Nyquist-Shannon theorem states that to reconstruct a signal without aliasing, it must be sampled at at least 2× its maximum frequency." },
          { question: "What is a low-pass filter?", choices: ["A filter that passes high frequencies", "A filter that passes low frequencies and attenuates high ones", "A filter that attenuates all frequencies", "A filter that only passes one frequency"], correct: 1, explanation: "A low-pass filter passes frequencies below its cutoff frequency and attenuates those above. Used for smoothing and anti-aliasing." },
          { question: "What is AM (Amplitude Modulation)?", choices: ["A technique where the carrier signal frequency varies with the information signal", "A technique where the carrier signal amplitude varies with the information signal", "An audio compression technique", "A type of digital encoding"], correct: 1, explanation: "In AM, the amplitude of the high-frequency carrier signal is modulated by the information signal. Used in AM radio broadcasting." },
          { question: "What is the FFT (Fast Fourier Transform)?", choices: ["A fast filter", "An efficient algorithm for computing the discrete Fourier transform in O(n log n)", "A type of modulation", "An audio compression standard"], correct: 1, explanation: "The FFT (Cooley-Tukey) computes the DFT in O(n log n) instead of O(n²), making real spectral processing possible on embedded processors." },
          { question: "What is convolution in signal processing?", choices: ["A matrix multiplication technique", "A mathematical operation that combines two signals to produce a third describing a system's response", "A type of adaptive filter", "A compression method"], correct: 1, explanation: "Convolution applies a system's impulse response to an input signal. Fundamental for digital filters and CNNs in AI." },
          { question: "What is the Signal-to-Noise Ratio (SNR)?", choices: ["The ratio between the useful signal power and noise power", "The ratio between maximum and minimum frequency", "The bandwidth of a channel", "The sampling frequency"], correct: 0, explanation: "SNR measures signal quality by comparing useful signal power to noise power. Expressed in dB: SNR = 10·log10(Psignal/Pnoise)." },
          { question: "What is PWM (Pulse Width Modulation)?", choices: ["A frequency modulation technique", "A technique that encodes information in the duration of pulses of a digital signal", "A type of digital filter", "A serial communication protocol"], correct: 1, explanation: "PWM varies the duty cycle of a square wave to encode an analog value. Used to control motor speed and LED brightness." },
        ]
      },

    ]
  },

  // ══════════════════════════════════════════════════════
  //  MATHEMATICS
  // ══════════════════════════════════════════════════════
  mathematiques: {
    label: "Mathematics",
    icon: "fa-solid fa-square-root-variable",
    color: "#059669",
    categories: [

      {
        name: "Linear Algebra",
        questions: [
          { question: "What is the dot product of two vectors?", choices: ["The sum of their components", "An operation that produces a scalar: Σ(ai × bi)", "The vector perpendicular to both vectors", "The product of their norms"], correct: 1, explanation: "The dot product is Σ(ai × bi). If the result is 0, the vectors are orthogonal. Fundamental in AI for computing similarities." },
          { question: "What is Singular Value Decomposition (SVD)?", choices: ["A matrix sorting algorithm", "A factorization of a matrix into three matrices U·Σ·V⊤", "A type of matrix multiplication", "A text compression algorithm"], correct: 1, explanation: "SVD decomposes any matrix into U·Σ·V⊤ where U and V are orthogonal and Σ is diagonal. Used for dimensionality reduction (PCA), image compression." },
          { question: "What is an invertible matrix?", choices: ["A matrix with negative values", "A square matrix whose determinant is non-zero and which admits an inverse matrix", "A symmetric matrix", "A matrix whose all elements are inverted"], correct: 1, explanation: "A square matrix A is invertible (non-singular) if det(A) ≠ 0. There exists A⁻¹ such that A·A⁻¹ = I." },
          { question: "What is an eigenvector?", choices: ["A unit vector", "A non-zero vector that does not change direction when a linear transformation is applied to it", "The vector with the largest norm in a matrix", "A vector orthogonal to all others"], correct: 1, explanation: "An eigenvector v satisfies A·v = λ·v, where λ is the eigenvalue. Fundamental for PCA, matrix diagonalization and understanding transformations." },
          { question: "What is the rank of a matrix?", choices: ["Its dimension (number of rows)", "The maximum number of linearly independent rows (or columns)", "The value of its determinant", "The number of non-zero elements"], correct: 1, explanation: "The rank of a matrix is the dimension of the vector space spanned by its columns (or rows). It indicates the number of 'true' dimensions represented." },
          { question: "What does the L2 norm of a vector represent?", choices: ["The sum of the absolute values of its components", "The square root of the sum of squares of its components (Euclidean distance)", "The maximum value of its components", "The sum of its components"], correct: 1, explanation: "The L2 norm (Euclidean norm) is ||v||₂ = √(Σvᵢ²). It is the geometric length of the vector in Euclidean space." },
          { question: "What is a diagonal matrix?", choices: ["A matrix without zero elements", "A square matrix whose off-diagonal elements are all zero", "A symmetric matrix", "An identity matrix"], correct: 1, explanation: "A diagonal matrix has non-zero elements only on the main diagonal. Multiplications and inversions are very simple with diagonal matrices." },
          { question: "What is the orthogonal projection of a vector onto another?", choices: ["The perpendicular vector", "The component of u in the direction of v: proj = (u·v / ||v||²) × v", "The cross product", "The normalized sum of the two vectors"], correct: 1, explanation: "The orthogonal projection of u onto v gives the component of u in the direction of v. Used in AI for embeddings and computational geometry." },
        ]
      },

      {
        name: "Discrete Mathematics",
        questions: [
          { question: "What is recurrence in discrete mathematics?", choices: ["A sequence defined in terms of its previous terms", "An infinite loop", "A type of mathematical proof", "A continuous function"], correct: 0, explanation: "A recurrence relation defines each term in terms of previous ones. E.g. Fibonacci: F(n) = F(n-1) + F(n-2), F(0)=0, F(1)=1." },
          { question: "What is propositional logic?", choices: ["A type of algebra", "A formal system using propositions (true/false) and logical connectives (AND, OR, NOT…)", "A communication protocol", "A type of proof by induction"], correct: 1, explanation: "Propositional logic manipulates boolean propositions with operators (∧ AND, ∨ OR, ¬ NOT, → implication, ↔ equivalence)." },
          { question: "What is combinatorics?", choices: ["A type of sorting algorithm", "The branch of mathematics studying counting, arrangement and combination of discrete structures", "A type of graph", "A formal proof method"], correct: 1, explanation: "Combinatorics studies ways to count, arrange and select objects. Fundamental in algorithmics and probability." },
          { question: "How many subsets does a set with n elements have?", choices: ["n!", "n²", "2ⁿ", "n·(n-1)"], correct: 2, explanation: "A set with n elements has 2ⁿ subsets (including the empty set and the set itself). Each element can be included (1) or excluded (0)." },
          { question: "What is a prime number?", choices: ["A number divisible by 2", "An integer greater than 1 divisible only by 1 and itself", "An odd number", "A number with no common factors with 10"], correct: 1, explanation: "A prime number is divisible only by 1 and itself (2, 3, 5, 7, 11…). Fundamental in cryptography (RSA relies on the difficulty of factoring large numbers)." },
          { question: "What is graph theory?", choices: ["The study of mathematical graphs and curves", "The study of structures composed of nodes (vertices) connected by edges", "A type of sorting algorithm", "The study of algebraic functions"], correct: 1, explanation: "Graph theory studies vertex-edge structures, used to model networks, social relationships, maps, circuits and many other problems." },
          { question: "What is the Euclidean algorithm?", choices: ["A sorting algorithm", "An algorithm for computing the greatest common divisor (GCD) of two integers", "An algorithm for finding prime numbers", "An encryption algorithm"], correct: 1, explanation: "The Euclidean algorithm computes the GCD via successive divisions: GCD(a,b) = GCD(b, a mod b) until b=0. Used in RSA cryptography." },
          { question: "What is mathematical induction?", choices: ["A type of scientific reasoning", "A proof method that demonstrates a property for n=base, then that if true for n, it is true for n+1", "A type of recursive algorithm", "A numerical computation method"], correct: 1, explanation: "Induction proves a property P(n) in two steps: P(base) is true, and P(n)→P(n+1). Like dominoes: if each knocks the next and the first falls…" },
        ]
      },

      {
        name: "Probability & Statistics",
        questions: [
          { question: "What is conditional probability P(A|B)?", choices: ["The probability that A and B occur together", "The probability that A occurs given that B has already occurred", "The probability that A occurs without B", "The sum of probabilities of A and B"], correct: 1, explanation: "P(A|B) = P(A∩B)/P(B). It is the probability that A occurs given that B has already happened. Fundamental in Bayesian classification and ML." },
          { question: "What is Bayes' theorem?", choices: ["P(A|B) = P(B|A)·P(A)/P(B)", "P(A|B) = P(A)+P(B)", "P(A|B) = P(A)·P(B)", "P(A|B) = 1-P(B|A)"], correct: 0, explanation: "Bayes' theorem: P(A|B) = P(B|A)·P(A)/P(B). It allows reversing conditional probabilities. The basis of Naive Bayes classifiers." },
          { question: "What is the variance of a distribution?", choices: ["The most frequent value", "A measure of the dispersion of values around the mean: E[(X-μ)²]", "The median value", "The difference between max and min"], correct: 1, explanation: "Variance measures the mean squared deviation from the mean. Standard deviation σ = √(variance) is more interpretable as it is in the same unit as the data." },
          { question: "What is the normal (Gaussian) distribution?", choices: ["A uniform probability distribution", "A bell-shaped symmetric distribution characterized by its mean μ and standard deviation σ", "A discrete probability distribution", "The law of large numbers"], correct: 1, explanation: "The normal distribution (bell curve) is the most common in statistics. Characterized by μ (center) and σ (width). The central limit theorem explains its ubiquity." },
          { question: "What is the correlation between two variables?", choices: ["Their causal relationship", "A measure of the strength and direction of their linear relationship, between -1 and +1", "Their covariance divided by variance", "The fact that they vary together"], correct: 1, explanation: "Pearson's correlation coefficient measures the linear relationship between -1 (perfect negative correlation) and +1 (positive). 0 indicates no linear correlation." },
          { question: "What is the law of large numbers?", choices: ["The larger a number, the more likely it is prime", "The sample mean of a large number of trials converges to the theoretical mean", "The probability of an event increases with the number of trials", "Large samples always follow a normal distribution"], correct: 1, explanation: "The law of large numbers guarantees that the average of a large number of independent identically distributed trials converges to the mathematical expectation." },
          { question: "What is a statistical hypothesis test?", choices: ["An algorithm performance test", "A procedure to decide whether data is compatible with a null hypothesis H₀", "A type of cross-validation", "A clustering algorithm"], correct: 1, explanation: "A hypothesis test (t-test, chi-square…) computes the probability (p-value) of observing the data if H₀ is true. If p < threshold (e.g. 0.05), we reject H₀." },
          { question: "What is linear regression?", choices: ["A classification algorithm", "A model that predicts a continuous value by finding the line minimizing the sum of squared errors", "A type of neural network", "A clustering method"], correct: 1, explanation: "Linear regression finds the relationship y = ax + b that minimizes the sum of squared residuals (least squares method). Foundation of many ML models." },
        ]
      },

    ]
  },

  // ══════════════════════════════════════════════════════
  //  CRYPTOGRAPHY
  // ══════════════════════════════════════════════════════
  cryptographie: {
    label: "Cryptography",
    icon: "fa-solid fa-lock",
    color: "#7c3aed",
    categories: [

      {
        name: "Cryptography Fundamentals",
        questions: [
          { question: "What is RSA encryption?", choices: ["A symmetric encryption", "An asymmetric encryption algorithm based on the difficulty of factoring large integers", "A hashing algorithm", "A shared key protocol"], correct: 1, explanation: "RSA relies on the mathematical difficulty of factoring the product of two large prime numbers. A public key encrypts, the private key decrypts." },
          { question: "What is a cryptographic hash function?", choices: ["A reversible encryption", "A one-way function that produces a fixed-size digest from variable-size data", "A symmetric encryption algorithm", "A key generator"], correct: 1, explanation: "A hash function (SHA-256, MD5…) produces a fixed-size hash. It is one-way (impossible to retrieve input from hash) and collision-resistant." },
          { question: "What is the Diffie-Hellman protocol?", choices: ["A simplified RSA encryption algorithm", "A key exchange protocol allowing two parties to share a secret over an unsecured channel", "A type of digital signature", "A password authentication protocol"], correct: 1, explanation: "Diffie-Hellman allows two parties to establish a shared secret key over a public channel, without ever transmitting the key itself. Based on the discrete logarithm problem." },
          { question: "What is a digital signature?", choices: ["A scan of a handwritten signature", "A cryptographic mechanism that guarantees the authenticity and integrity of a message", "A type of SSL certificate", "A type of symmetric encryption"], correct: 1, explanation: "A digital signature is created with the sender's private key and verifiable with their public key. It guarantees the message comes from them and hasn't been modified." },
          { question: "What is the AES algorithm?", choices: ["An asymmetric algorithm", "A standard symmetric block cipher (128 bits) adopted by NIST in 2001", "A hashing protocol", "A key exchange protocol"], correct: 1, explanation: "AES (Advanced Encryption Standard) is the world standard for symmetric encryption. It operates on 128-bit blocks with 128, 192 or 256-bit keys." },
          { question: "What is an X.509 certificate?", choices: ["A security training certificate", "A standard digital certificate format binding a public key to an identity, signed by a certificate authority", "A type of encryption protocol", "An electronic signature standard"], correct: 1, explanation: "An X.509 certificate associates a public key with an identity (domain, person, organization). It is signed by a Certificate Authority (CA) to guarantee authenticity." },
          { question: "What is salt in password hashing?", choices: ["A secure hashing algorithm", "A random value added to the password before hashing to prevent rainbow table attacks", "A type of asymmetric encryption", "A password derivation key"], correct: 1, explanation: "Salt is a unique random value added to each password before hashing. It renders rainbow tables useless and ensures two users with the same password have different hashes." },
          { question: "What does TLS 1.3 bring compared to TLS 1.2?", choices: ["It is slower but more secure", "It removes weak cipher suites, reduces handshake latency and enforces forward secrecy", "It uses RSA exclusively", "It is incompatible with older browsers"], correct: 1, explanation: "TLS 1.3: removal of obsolete algorithms (RSA key exchange, RC4, SHA-1), 1-RTT handshake (vs 2-RTT), mandatory forward secrecy, enhanced metadata protection." },
          { question: "What is forward secrecy?", choices: ["Encryption that works offline", "The property guaranteeing that compromise of the long-term private key doesn't compromise past sessions", "A type of symmetric key protocol", "A certificate verification mechanism"], correct: 1, explanation: "Forward secrecy (via ECDHE) generates ephemeral session keys. Even if the server's private key is compromised later, past sessions remain secure." },
          { question: "What is a brute force attack on encryption?", choices: ["A physical attack on servers", "Systematically trying all possible keys until finding the right one", "An attack exploiting mathematical flaws", "A social engineering technique"], correct: 1, explanation: "A brute force attack tests all possible key combinations. AES-256 has 2²⁵⁶ possible keys — with all current computing power, this is computationally infeasible." },
          { question: "What is Elliptic Curve Cryptography (ECC)?", choices: ["Encryption based on elliptic matrices", "Asymmetric cryptography based on elliptic curve algebra, offering shorter keys at equivalent security", "A type of hashing protocol", "A symmetric signature algorithm"], correct: 1, explanation: "ECC offers the same security level as RSA with much shorter keys (256-bit ECC ≈ 3072-bit RSA). Ideal for embedded and mobile systems." },
          { question: "What is a side-channel attack?", choices: ["A network attack on a secondary channel", "An attack that exploits physical information (execution time, power consumption, radiation) of a system", "A man-in-the-middle attack", "An attack on the TLS protocol"], correct: 1, explanation: "Side-channel attacks exploit indirect physical information rather than mathematical flaws: timing attacks, power analysis (DPA), acoustic attacks." },
        ]
      },

    ]
  },

  // ══════════════════════════════════════════════════════
  //  COMPILATION & LANGUAGES
  // ══════════════════════════════════════════════════════
  compilation: {
    label: "Compilation & Languages",
    icon: "fa-solid fa-code",
    color: "#0891b2",
    categories: [

      {
        name: "Compilation",
        questions: [
          { question: "What are the main phases of a compiler?", choices: ["Read, Execute, Output", "Lexical analysis, Syntax analysis, Semantic analysis, Code generation, Optimization", "Parsing, Linking, Execution", "Tokenization, Interpretation, Debugging"], correct: 1, explanation: "A compiler goes through: lexical analysis (tokens), syntax (AST), semantic (types), intermediate code generation, optimization, target code generation." },
          { question: "What is a token (lexeme) in lexical analysis?", choices: ["A syntax error", "The smallest meaningful unit of a program (keyword, identifier, operator, literal)", "A comment in the code", "An uninitialized variable"], correct: 1, explanation: "The lexer breaks source code into tokens: keywords (if, while), identifiers (myVariable), operators (+, =), literals (42, 'hello'), delimiters ({, ;)." },
          { question: "What is an AST (Abstract Syntax Tree)?", choices: ["A binary search tree", "An abstract tree representation of the syntactic structure of a program", "A type of symbol table", "A code optimization tree"], correct: 1, explanation: "The AST is a hierarchical representation of the program after syntax analysis. Each node represents a language construct (expression, statement, declaration)." },
          { question: "What is BNF (Backus-Naur Form) grammar?", choices: ["A programming language from the 1960s", "A formal notation for describing the syntax of a programming language", "A type of syntax analyzer", "A code documentation format"], correct: 1, explanation: "BNF is a meta-syntax for describing context-free grammars. It defines production rules of a language: expr ::= term '+' expr | term." },
          { question: "What is a linker?", choices: ["A debugging tool", "A program that combines multiple compiled object files into a single executable by resolving external references", "A type of compiler", "A bytecode interpreter"], correct: 1, explanation: "The linker resolves references between modules (functions called in other files), links libraries and produces the final executable or library." },
          { question: "What is bytecode (intermediate code)?", choices: ["The final assembly code", "Portable intermediate code executed by a virtual machine", "A type of optimized code", "Native binary code"], correct: 1, explanation: "Bytecode (Java .class, Python .pyc) is portable intermediate code executed by a VM (JVM, CPython). More portable than native code, less performant." },
          { question: "What is JIT (Just-In-Time) compilation?", choices: ["A slow and precise compilation", "A technique that compiles bytecode into native code at runtime to improve performance", "A type of code interpretation", "A real-time compiler"], correct: 1, explanation: "JIT compilation (JVM HotSpot, V8 for JS) compiles bytecode into native machine code at runtime, combining bytecode portability with native code performance." },
          { question: "What is type checking?", choices: ["Verifying the syntax of code", "Analysis that verifies operations are applied to compatible data types", "Detecting memory leaks", "Loop optimization"], correct: 1, explanation: "Type checking (static or dynamic) verifies type consistency: not adding an integer and an object, functions receiving the right argument types." },
          { question: "What is a Context-Free Grammar (CFG)?", choices: ["A grammar used outside its original context", "A grammar whose production rules have a single non-terminal on the left, independently of context", "A type of grammar for natural languages", "A grammar without recursive rules"], correct: 1, explanation: "A CFG defines rules A → α without conditions on the environment of A. Most programming languages are described by CFGs." },
          { question: "What is the compiler optimization 'inline expansion'?", choices: ["Expanding stack memory", "Replacing a function call with the function body to avoid call overhead", "Optimizing nested loops", "Reducing executable size"], correct: 1, explanation: "Inlining substitutes a function call with the function's code itself. Eliminates call overhead (saving registers, pushing arguments) at the cost of larger code." },
        ]
      },

      {
        name: "Automata & Formal Languages",
        questions: [
          { question: "What is a Deterministic Finite Automaton (DFA)?", choices: ["An automaton with infinite memory", "A computation model with a finite number of states, a deterministic transition function and accepting states", "A type of Turing machine", "A probabilistic automaton"], correct: 1, explanation: "A DFA recognizes regular languages. For each state and input symbol, there is exactly one possible transition." },
          { question: "What is a regular expression (regex)?", choices: ["A complex mathematical formula", "A concise notation for describing regular languages and text patterns", "A type of context-free grammar", "A text search algorithm"], correct: 1, explanation: "A regex describes text patterns with operators (., *, +, ?, [], |, ^, $). They correspond exactly to languages recognizable by finite automata." },
          { question: "What is the pumping lemma for regular languages?", choices: ["A lemma on data compression", "A tool to prove that a language is not regular", "A technique for optimizing automata", "A theorem on the complexity of regular expressions"], correct: 1, explanation: "The pumping lemma allows demonstrating that a language is not regular: if for every sufficiently long word, you cannot 'pump' a substring, the language is not regular." },
          { question: "What is a Turing machine?", choices: ["A 1940s computer", "An abstract computation model with an infinite tape and a read/write head, equivalent in power to modern computers", "A type of finite automaton", "A logic circuit model"], correct: 1, explanation: "The Turing machine (Alan Turing, 1936) is the universal computation model. Anything that can be computed algorithmically can be computed by a Turing machine." },
          { question: "What is the Chomsky hierarchy?", choices: ["A ranking of programming languages by popularity", "A classification of formal grammars in 4 levels according to their expressive power", "A type of automata theory", "A compilation model"], correct: 1, explanation: "The Chomsky hierarchy classifies grammars: Type 0 (unrestricted, Turing-complete), Type 1 (context-sensitive), Type 2 (context-free, most PLs), Type 3 (regular)." },
          { question: "What is the Halting Problem?", choices: ["The computer startup problem", "The undecidable problem of determining whether an arbitrary program will stop or run indefinitely on a given input", "A type of infinite loop", "A process synchronization problem"], correct: 1, explanation: "Turing proved in 1936 that no general algorithm can determine whether an arbitrary program halts. It is the first known undecidable problem." },
        ]
      },

    ]
  },

  // ══════════════════════════════════════════════════════
  //  DISTRIBUTED SYSTEMS
  // ══════════════════════════════════════════════════════
  systemes_distribues: {
    label: "Distributed Systems",
    icon: "fa-solid fa-network-wired",
    color: "#0f766e",
    categories: [

      {
        name: "Distributed Systems",
        questions: [
          { question: "What is the CAP theorem?", choices: ["A theorem on algorithm complexity", "A theorem stating that a distributed system cannot simultaneously guarantee Consistency, Availability and Partition tolerance", "A distributed consensus protocol", "A data replication model"], correct: 1, explanation: "The CAP theorem (Brewer, 2000): a distributed system can only guarantee 2 of 3 — Consistency, Availability, Partition tolerance — simultaneously." },
          { question: "What is the Paxos consensus algorithm?", choices: ["A P2P network protocol", "A consensus algorithm allowing distributed nodes to agree on a value despite failures", "A type of database replication", "A leader election protocol"], correct: 1, explanation: "Paxos (Lamport) is a fault-tolerant consensus algorithm. It guarantees a set of nodes agree on a single value, even if some fail." },
          { question: "What is the Raft algorithm?", choices: ["A distributed sorting algorithm", "A consensus algorithm alternative to Paxos, easier to understand and implement", "A master-slave replication protocol", "A data partitioning algorithm"], correct: 1, explanation: "Raft (Ongaro & Ousterhout, 2014) is a consensus algorithm designed to be more understandable than Paxos. Used in etcd, CockroachDB, TiKV." },
          { question: "What is eventual consistency?", choices: ["Immediate consistency of all replicas", "A guarantee that replicas will converge to the same state if no updates are made for long enough", "A type of distributed transaction", "Real-time data consistency"], correct: 1, explanation: "Eventual consistency (DynamoDB, Cassandra) accepts potentially stale reads in exchange for high availability. Replicas converge over time." },
          { question: "What is a Peer-to-Peer (P2P) system?", choices: ["A network with a central server", "A decentralized network where each node can act as both client and server", "A secure communication protocol", "A type of distributed database"], correct: 1, explanation: "In a P2P network (BitTorrent, blockchain), each peer can share resources directly with others without a central server, offering resilience and scalability." },
          { question: "What is the Byzantine Generals Problem?", choices: ["A routing algorithm problem", "A distributed consensus problem where some nodes can send incorrect or malicious information", "A type of network attack", "A clock synchronization problem"], correct: 1, explanation: "The Byzantine problem (Lamport) models systems where some nodes can be faulty or malicious. Byzantine Fault Tolerance (BFT) is fundamental in blockchains." },
          { question: "What is Map-Reduce?", choices: ["A distributed sorting algorithm", "A programming model for parallel processing of large datasets on a cluster", "A file replication protocol", "A type of NoSQL database"], correct: 1, explanation: "Map-Reduce (Google, 2004) decomposes processing into a Map phase (parallel transformation) and a Reduce phase (aggregation). The basis of Hadoop." },
          { question: "What is a Lamport clock?", choices: ["An NTP synchronization protocol", "A logical timestamp mechanism for ordering events in a distributed system without a shared physical clock", "A consensus algorithm", "A type of distributed lock"], correct: 1, explanation: "Lamport clocks assign incrementing logical timestamps to events. They establish a partial causal ordering between distributed events." },
          { question: "What is leader-follower replication?", choices: ["A type of microservice", "A scheme where a leader node accepts writes and replicates them to followers that serve reads", "A P2P consensus protocol", "A type of database partitioning"], correct: 1, explanation: "In leader-follower replication (MySQL, PostgreSQL, Redis), the leader accepts all writes and propagates them to replicas. Followers serve reads, improving scalability." },
          { question: "What is the circuit breaker pattern in microservices?", choices: ["An electrical circuit breaker", "A pattern that automatically interrupts calls to a failing service to prevent cascade failures", "A type of load balancer", "A network security mechanism"], correct: 1, explanation: "The circuit breaker (Hystrix, Resilience4j) monitors service failures. Beyond a threshold, it 'opens' and returns a fast error without calling the service, protecting the system." },
        ]
      },

    ]
  },

};
